# Generated by Django 3.0.2 on 2020-01-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files_storage',
            options={'verbose_name': 'File Storage', 'verbose_name_plural': 'File Storage'},
        ),
    ]
