# Generated by Django 2.2.9 on 2020-01-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0002_auto_20200104_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='files_storage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
