# Generated by Django 3.0.2 on 2020-01-04 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='design_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Design_package', verbose_name='Design package'),
        ),
        migrations.AddField(
            model_name='projects',
            name='passwords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projects',
            name='percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project_managers', verbose_name='Project Manager'),
        ),
        migrations.AddField(
            model_name='projects',
            name='rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Resident_managers', verbose_name='Resident Manager'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
