# Generated by Django 3.0.2 on 2020-01-04 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200104_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_managers',
            options={'verbose_name': 'Project Manager', 'verbose_name_plural': 'Project Managers'},
        ),
        migrations.AlterModelOptions(
            name='resident_managers',
            options={'verbose_name': 'Resident Manager', 'verbose_name_plural': 'Resident Managers'},
        ),
        migrations.RemoveField(
            model_name='project_managers',
            name='address',
        ),
        migrations.RemoveField(
            model_name='resident_managers',
            name='address',
        ),
    ]
