# Generated by Django 3.0.2 on 2020-01-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200104_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('order_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project Manager',
                'verbose_name_plural': 'Project Managers',
            },
        ),
        migrations.AlterModelOptions(
            name='design_package',
            options={'verbose_name': 'Design Package', 'verbose_name_plural': 'Design Packages'},
        ),
    ]
