# Generated by Django 3.0.2 on 2020-01-04 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200104_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general_contractor',
            options={'verbose_name': 'General Contractor', 'verbose_name_plural': 'General Contractors'},
        ),
    ]
