# Generated by Django 3.0.2 on 2020-01-04 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200104_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='design_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.General_contractor', verbose_name='General Contractor'),
        ),
    ]
