# Generated by Django 3.0.2 on 2020-01-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200104_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('EL', 'Electric'), ('PL', 'Plumbing'), ('BU', 'Building'), ('PA', 'Parking')], max_length=2)),
                ('file', models.FileField(blank=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permit',
                'verbose_name_plural': 'Permits',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='permits',
            field=models.ManyToManyField(to='projects.Permit'),
        ),
    ]
