# Generated by Django 3.0.2 on 2020-01-04 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200104_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='inspections',
        ),
        migrations.AddField(
            model_name='inspection',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='inspection_type',
            name='category',
            field=models.CharField(choices=[('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Building', 'Building')], max_length=255),
        ),
    ]
