# Generated by Django 3.0.2 on 2020-01-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200104_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='status',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Partial', 'Partial'), ('Scheduled', 'Scheduled')], default='Scheduled', max_length=255),
        ),
    ]
