# Generated by Django 2.2.9 on 2020-01-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20200104_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='permits',
        ),
        migrations.AddField(
            model_name='project',
            name='permits',
            field=models.ManyToManyField(to='projects.Permit'),
        ),
    ]
