# Generated by Django 2.2.9 on 2020-01-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20200104_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='city_state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='unit',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='zip',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='legal_entity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='portfolio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
