# Generated by Django 2.2.9 on 2020-01-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20200115_1441'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permit',
        ),
    ]
