# Generated by Django 2.2.9 on 2020-01-19 21:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_delete_permit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_managers.Project_manager', verbose_name='Project Manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resident_managers.Resident_manager', verbose_name='Resident Manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Done', 'Done'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected')], default='OPEN', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.DeleteModel(
            name='Project_managers',
        ),
        migrations.DeleteModel(
            name='Resident_managers',
        ),
    ]
