# Generated by Django 2.2.9 on 2020-01-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20200119_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bathrooms',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='bedrooms',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='city_state',
            field=models.CharField(default='San Francisco, CA', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='jobNumber',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='percent',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='sqFt',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Done', 'Done'), ('Canceled', 'Canceled'), ('Rejected', 'Rejected')], default='Open', max_length=255),
        ),
    ]
