# Generated by Django 2.2.9 on 2020-01-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20200123_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sqFt',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, default='1970-01-01'),
        ),
    ]
