# Generated by Django 2.2.9 on 2020-01-27 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0003_files_storage_description'),
        ('projects', '0020_auto_20200123_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='file_storage.Files_storage'),
        ),
        migrations.AddField(
            model_name='project',
            name='rq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rqs', to='file_storage.Files_storage'),
        ),
    ]
