# Generated by Django 2.2.9 on 2020-01-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0003_files_storage_description'),
        ('projects', '0021_auto_20200127_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(related_name='documents', to='file_storage.Files_storage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='drawings',
            field=models.ManyToManyField(related_name='drawings', to='file_storage.Files_storage'),
        ),
    ]
