# Generated by Django 2.2.9 on 2020-01-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20200127_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(related_name='documents', to='documents.Document'),
        ),
    ]
