# Generated by Django 2.2.9 on 2020-01-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_item',
            name='qty',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
