# Generated by Django 2.2.9 on 2020-01-29 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20200129_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_item',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
    ]
