# Generated by Django 2.2.9 on 2020-01-31 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20200129_1101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice_item',
        ),
    ]
