# Generated by Django 2.2.9 on 2020-01-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='end_date',
            field=models.DateField(blank=True, default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='start_date',
            field=models.DateField(blank=True, default='1970-01-01'),
        ),
    ]
