# Generated by Django 2.2.9 on 2020-01-19 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_auto_20200116_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permits', to='projects.Project'),
        ),
    ]
