# Generated by Django 2.2.9 on 2020-01-31 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0004_delete_invoice_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('unit_price', models.FloatField(blank=True, default=0)),
                ('qty', models.FloatField(blank=True, default=1)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.Invoice')),
            ],
        ),
    ]
