# Generated by Django 2.2.9 on 2020-01-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_log',
            name='status',
            field=models.CharField(choices=[('Holding', 'Holding'), ('Prioritized', 'Prioritized'), ('Started', 'Started'), ('Finished', 'Finished')], default='Holding', max_length=255),
        ),
    ]
