# Generated by Django 2.2.9 on 2020-01-28 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200128_1118'),
        ('change_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change_order',
            options={},
        ),
        migrations.RemoveField(
            model_name='change_order',
            name='date',
        ),
        migrations.RemoveField(
            model_name='change_order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='change_order',
            name='files',
        ),
        migrations.RemoveField(
            model_name='change_order',
            name='number',
        ),
        migrations.AddField(
            model_name='change_order',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='change_order',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project'),
        ),
    ]
