# Generated by Django 2.2.9 on 2020-01-29 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20200129_1008'),
        ('change_orders', '0002_auto_20200128_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='change_order',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.Invoice'),
        ),
    ]
