# Generated by Django 2.2.9 on 2020-01-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20200128_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='document',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='document',
            name='payer',
        ),
        migrations.AddField(
            model_name='document_type',
            name='postfix',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document_type',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document_type',
            name='start',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
