# Generated by Django 2.2.9 on 2020-01-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0004_auto_20200113_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
