# Generated by Django 2.2.9 on 2020-01-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0006_auto_20200113_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='amount',
            field=models.FloatField(blank=True),
        ),
    ]
