# Generated by Django 2.2.9 on 2020-01-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0007_auto_20200113_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
