# Generated by Django 2.2.9 on 2020-01-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0009_auto_20200114_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='amount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
