# Generated by Django 2.2.9 on 2020-01-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0010_auto_20200114_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
