# Generated by Django 2.2.9 on 2020-01-15 21:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Building', 'Building')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inspection Type',
                'verbose_name_plural': 'Inspection Types',
            },
        ),
    ]
