# Generated by Django 2.2.9 on 2020-01-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='is_meal_time',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='clock_in',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='clock_out',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='is_holiday',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='is_weekend',
            field=models.BooleanField(blank=True),
        ),
    ]
