# Generated by Django 2.2.9 on 2020-01-20 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file_storage', '0003_files_storage_description'),
        ('suppliers', '0001_initial'),
        ('projects', '0018_auto_20200119_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending ', 'Pending '), ('Awaiting Payment', 'Awaiting Payment'), ('Awaiting Fulfillment', 'Awaiting Fulfillment'), ('Awaiting Shipment', 'Awaiting Shipment'), ('Awaiting Pickup', 'Awaiting Pickup'), ('Partially Shipped', 'Partially Shipped'), ('Completed', 'Completed'), ('Shipped', 'Shipped'), ('Canceled', 'Canceled'), ('Declined', 'Declined'), ('Refunded', 'Refunded'), ('Disputed', 'Disputed'), ('Manual Verification Required', 'Manual Verification Required'), ('Partially Refunded', 'Partially Refunded')], default='Pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('files', models.ManyToManyField(to='file_storage.Files_storage')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='projects.Project')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='suppliers.Supplier')),
            ],
        ),
    ]
