# Generated by Django 2.2.9 on 2020-01-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Awaiting Payment', 'Awaiting Payment'), ('Awaiting Fulfillment', 'Awaiting Fulfillment'), ('Awaiting Shipment', 'Awaiting Shipment'), ('Awaiting Pickup', 'Awaiting Pickup'), ('Partially Shipped', 'Partially Shipped'), ('Completed', 'Completed'), ('Shipped', 'Shipped'), ('Canceled', 'Canceled'), ('Declined', 'Declined'), ('Refunded', 'Refunded'), ('Disputed', 'Disputed'), ('Manual Verification Required', 'Manual Verification Required'), ('Partially Refunded', 'Partially Refunded')], default='Pending', max_length=255),
        ),
    ]
